laravel/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', 'HomeController@frontpage');
Route::post('contacto', 'HomeController@contacto');
/* Calendario Publico INICIO*/
Route::get('agendas/calendario/{shortname?}/{grupo?}', array('as' => 'agenda.calendario', 'uses' => 'AgendasController@calendario'));
Route::get('reservas/events', array('as' => 'reservas.eventos', 'uses' => 'ReservasController@getEvents'));
Route::post('reservas/guardar', array('uses' => 'ReservasController@guardar'));
Route::post('reservas/horarioDisponible', array('as' => 'reservas.horario-disponible', 'uses' => 'ReservasController@horarioDisponible'));
Route::post('rango/precio', array('as' => 'rangos.precio', 'uses' => 'RangosController@getPrecio'));
Route::post('reservas', array('as' => 'reservas.store', 'uses' => 'ReservasController@store'));

/* Calendario Publico FIN */
/* Pago Reserva */
Route::get('pagos/proceso_reserva/{cliente_id}/{reserva_id?}', array('as'=>'pagos.procesoreserva','uses'=> 'PagosController@procesoReserva'));
Route::post('pagos/exito', array('uses'=> 'PagosController@exito'));
Route::post('pagos/fracaso', array('uses'=> 'PagosController@fracaso'));
Route::get('pagos/confirmarOrden', array('uses'=> 'PagosController@confirmarOrden')); // Antes del envio
Route::get('pagos/proceso_plan/{cliente_id}/{plan_id}', array('uses'=> 'PagosController@procesoPlan'));
//Flow function
// Route::get('flows/testconfirm',array('uses' => 'FlowsController@testConfirm'));
Route::post('flows/confirmar',array('uses' => 'FlowsController@confirmar')); // Duarnte el proceso de compra

Route::group(array('before' => 'auth'), function()
{
	//Admin
	Route::get('admin','AdminController@createClient');

	Route::get('portal', array('as' => 'portal', 'uses' => 'HomeController@dashboard'));
	Route::get('wiki','HomeController@wiki');

	//Pagos
	Route::resource('pagos', 'PagosController');

	//Horarios
	Route::resource('horarios', 'HorariosController');
	//Reservas
	Route::get('reservas/calendario/{grupo?}', array('as' => 'reservas.calendario', 'uses' => 'ReservasController@calendario'));
	Route::resource('reservas', 'ReservasController', array('except' => array('store','show')));

	//Route::get('rangos/{idplaza}', array('as' => 'rangos.index', 'uses'=>'RangosController@index'));
	//Route::get('agendas.rangos', array( 'uses'=>'RangosController@index'));

	//Agendas
	Route::resource('agendas', 'AgendasController');
	// Agregar Grupo
	Route::get('agenda_grupos/defecto/{id}', array('as' => 'agenda_grupos.defecto', 'uses' => 'AgendaGruposController@defecto'));
	Route::get('agenda_grupos/estado/{id}', array('as' => 'agenda_grupos.estado', 'uses' => 'AgendaGruposController@estado'));
	Route::resource('agenda_grupos', 'AgendaGruposController');
	//Rangos
	Route::get('agendas/{agendas}/diaa/{dia}', array('as' => 'agendas.rangos.new', 'uses' => 'RangosController@create'));
	Route::post('agendas/{agendas}/rangos', array('as' => 'agendas.rangos.store', 'uses' => 'RangosController@store'));
	Route::get('agendas/{agendas}/diar/{dia}', array('as' => 'agendas.rangos.duplicate', 'uses' => 'RangosController@duplicate'));
	Route::resource('agendas.rangos', 'RangosController', array('except' => array('create','store','edit','update')));
	//Precios Especiales
	Route::resource('precio_especiales', 'PrecioEspecialesController');

	Route::get('clientes/planCaducado/{cliente_id}',array('uses'=>'ClientesController@planCaducado'));
	Route::get('clientes/planUpgrade/{cliente_id}',array('uses'=>'ClientesController@planUpgrade'));

	Route::get('clientes/flowConfigIs/{cliente_id}', array( 'uses'=>'ClientesController@flowConfigIs')); // existe
	Route::get('clientes/flowConfig/{cliente_id}', array('as' =>'flowconfig.create', 'uses'=>'ClientesController@flowConfig')); // Crear
	Route::post('clientes/flowConfigStore/', array( 'uses'=>'ClientesController@flowConfigStore')); // Guardar
	Route::get('clientes/flowConfigShow/{cliente_id?}', array('as' =>'flowconfig.show',  'uses'=>'ClientesController@flowConfigShow')); // Ver
	Route::post('clientes/flowCertificate/', array( 'uses'=>'ClientesController@flowCertificate')); // descargar Certificado

	Route::get('exportar/reservas', array('uses' => 'ReservasController@exportReservas'));

	//
	Route::get('usuarios',array('as'=>'usuarios','uses'=>'UsersController@usuarioIndex'));
	Route::get('usuarios/create',array('as'=>'usuarios.create','uses'=>'UsersController@usuarioCreate'));
	Route::post('usuarios/store',array('as'=>'usuarios.store','uses'=>'UsersController@usuariostore'));
	Route::get('usuarios/{usuario_id}/edit',array('as'=>'usuarios.edit','uses'=>'UsersController@usuarioEdit'));
	Route::put('usuarios/{usuario_id}',array('as'=>'usuarios.update','uses'=>'UsersController@usuarioUpdate'));
	Route::delete('usuarios/{usuario_id}',array('as'=>'usuarios.destroy','uses'=>'UsersController@usuarioDestroy'));

	// Perfil
	Route::get('users/perfil', 'UsersController@perfil');
	Route::post('users/perfils', 'UsersController@perfilStore');
});

// Pruebas
Route::controller('pruebas','PruebasController');
// Confide routes

Route::get('users/create', 'UsersController@create');
Route::post('users', 'UsersController@store');
Route::get('users/login', array('as' => 'login', 'uses' => 'UsersController@login'));
Route::post('users/login', 'UsersController@doLogin');
Route::get('users/confirm/{code}', 'UsersController@confirm');
Route::get('users/forgot_password', 'UsersController@forgotPassword');
Route::post('users/forgot_password', 'UsersController@doForgotPassword');
Route::get('users/reset_password/{token}', 'UsersController@resetPassword');
Route::post('users/reset_password', 'UsersController@doResetPassword');
Route::get('users/logout', 'UsersController@logout');

laravel/app/models/Rango.php
<?php

class Rango extends \Eloquent {
	protected $table = 'rango';
  protected $primaryKey = 'ID_RANGO';
  public $timestamps = false;
	
	protected $fillable = ['id_plaza','dia','desde','hasta','valor'];
	// Add your validation rules here
	public static $rules = [
		// 'title' => 'required'
	];

  public function agenda()
  {
    return $this->belongsTo('Agenda','ID_PLAZA');
  }



  public function __get($key)
  {
    if (is_null($this->getAttribute($key))) {
        return $this->getAttribute(strtoupper($key));
    } else {
        return $this->getAttribute($key);
    }
  }

}

laravel/app/controllers/RangosController.php
<?php

class RangosController extends \BaseController {

	/**
	 * Display a listing of rangos
	 *
	 * @return Response
	 */
	public function index($idplaza)
	{
		$agenda_id = $idplaza;
		$agenda =  Agenda::find($agenda_id);
		$tipo = $tipo = Config::get('variables.tipo_agenda');
		$rangos_temp = $agenda->rangos;

		// dd(DB::getQueryLog());
		$dias = array(1 => 'Lunes',2 => 'Martes', 3 => 'Miercoles', 4 => 'Jueves' , 5 => 'Viernes', 6 => 'Sabado', 7 => 'Domingo');

		foreach ($rangos_temp as $r_t) {
			
			$rangos[$r_t->dia][$r_t->id_rango]['desde'] = $r_t->desde;
			$rangos[$r_t->dia][$r_t->id_rango]['hasta'] = $r_t->hasta;
			$rangos[$r_t->dia][$r_t->id_rango]['valor'] = $r_t->valor;
		}
		//dd($rangos);

		return View::make('rangos.index', compact('rangos','agenda','dias'))->withTipo($tipo);
	}

	/**
	 * Show the form for creating a new rango
	 *
	 * @return Response
	 */
	public function create($agendaid, $diaa)
	{
		$dayNames = array(
	    'Domingo',
	    'Lunes', 
	    'Martes', 
	    'Miercoles', 
	    'Jueves', 
	    'Viernes', 
	    'Sabado', 
	 );
		$agenda =  Agenda::find($agendaid);
		$data = array(
			'agenda_id' => $agendaid, 
			'dia' => $diaa,
			'dia_nombre' => ($diaa != 7)?$dayNames[$diaa]:$dayNames[0]
		);
		
		if($agenda->tipo != 1440){
			$ultimaHora = Rango::where('ID_PLAZA','=',$agendaid)->where('DIA', '=', $diaa)->max('HASTA');
			if($ultimaHora){
				$horaInicio = (int) str_replace(':00:00','',$ultimaHora);
				// TODO: Esto se debe definir por el intervalo de tiempo definido en la agenda
				$horaFin = ($horaInicio+1); 
			}else{
				$horaInicio = 8;
				$horaFin = 9;
			}
			$data['horaInicio'] = $horaInicio;
			$data['horaFin'] = $horaFin;
		}

		
		
		return View::make('rangos.create', $data, compact('agenda'));
	}

	/**
	 * Store a newly created rango in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$validator = Validator::make($data = Input::all(), Rango::$rules);

		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator)->withInput();
		}

		Rango::create($data);
		$agendaid = $data['id_plaza'];
		return Redirect::route('agendas.rangos.index', array('agendas' => $agendaid));
	}

	/**
	 * Display the specified rango.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	// public function show($id)
	// {
	// 	$rango = Rango::findOrFail($id);

	// 	return View::make('rangos.show', compact('rango'));
	// }

	/**
	 * Show the form for editing the specified rango.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	// public function edit($id)
	// {
	// 	$rango = Rango::find($id);

	// 	return View::make('rangos.edit', compact('rango'));
	// }

	/**
	 * Update the specified rango in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	// public function update($id)
	// {
	// 	$rango = Rango::findOrFail($id);

	// 	$validator = Validator::make($data = Input::all(), Rango::$rules);

	// 	if ($validator->fails())
	// 	{
	// 		return Redirect::back()->withErrors($validator)->withInput();
	// 	}

	// 	$rango->update($data);

	// 	return Redirect::route('rangos.index');
	// }

	/**
	 * Remove the specified rango from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($agendaid, $id)
	{
		//corroborar que la plaza de la cual se esta borrando el rango, es del cliente que esta logueado
		//Rango::destroy($id);
		Rango::where('ID_PLAZA', '=',$agendaid)->where('ID_RANGO', '=',$id)->delete();
		
		return Redirect::route('agendas.rangos.index', array('agendas' => $agendaid));
	}

	public function duplicate($agendaid, $idr)
	{
		# code...
	}

	public function getPrecio()
	{
		$data = Input::all();
		//$data['hora_ini'] = substr($data['hora_ini'], 0, 2);
		//$data['hora_fin'] = substr($data['hora_fin'], 0, 2);
		
		// Precio espcial todos el dia
		// TODO: Deberia considerar tambien los horios en el dia completo?
		$precio_especial_dia = DB::table('precio_especial')
												->leftJoin('detalle_precio_especial','precio_especial.id_especial','=','detalle_precio_especial.id_especial')
												->where('precio_especial.id_cliente', '=', $data['cliente_id'])
												->where('detalle_precio_especial.id_plaza', '=', $data['id_plaza'])
												->where('precio_especial.dia_tipo', '=', date('N', strtotime($data['dia'].'-'.$data['mes'].'-'.$data['anho'])))
												->first(['valor']);
		// Precio espcial hora espesifica
		$precio_especial_fecha = DB::table('precio_especial')
												->leftJoin('detalle_precio_especial','precio_especial.id_especial','=','detalle_precio_especial.id_especial')
												->where('precio_especial.id_cliente', '=', $data['cliente_id'])
												->where('detalle_precio_especial.id_plaza', '=', $data['id_plaza'])
												->where('precio_especial.dia', '=', $data['dia'])
												->where('precio_especial.mes', '=', $data['mes'])
												->where('precio_especial.anho', '=', $data['anho'])
												->where('precio_especial.hora_inicio', '<=',$data['hora_ini'])
												->where('precio_especial.hora_fin', '>=',$data['hora_fin'])
												->first(['valor']);

		// Precio rango de Hora
		$precio_rango = Rango::where('id_plaza', '=', $data['id_plaza'])
													->where('dia', '=', date('N', strtotime($data['dia'].'-'.$data['mes'].'-'.$data['anho'])))
													->where('desde', '<=', $data['hora_ini'])
													->where('hasta', '>=', $data['hora_fin'])
													->first(['valor']);

		if(isset($precio_especial_dia->valor))
		{
    	$valor = $precio_especial_dia->valor;
    }elseif(isset($precio_especial_fecha->valor))
    {
    	$valor = $precio_especial_fecha->valor;
    }else{
    	$valor = $precio_rango->valor;
    }
		// TODO: Mostrara error si no existe valor para el rango seleccionado.
    // $dataArray['valor'] = $valor;
    $dataArray['valor'] = $valor;
		debug($precio_especial_dia);
		debug($precio_especial_fecha);
		debug($precio_rango);
		return json_encode($dataArray);
	}	

}

laravel/app/views/rangos/create.blade.php
@extends('layout.default')

@section('main')
<h1>Rangos para "{{ $agenda->nombre }}" para el dia {{ $dia_nombre }}</h1>
<div class="col-md-10">
  <div class="row">
    <div class="col-md-11" style="top:15px;">

      {{ Form::open(array('route'=> 'agendas.rangos.store')) }}      
      <input type="hidden" name="id_plaza" value="{{ $agenda_id }}">
      <input type="hidden" name="dia" value="{{ $dia }}">
      @if($agenda->tipo == 1440)
      <input type="hidden" name="desde" value="00:00:00">
      <input type="hidden" name="hasta" value="23:59:00">
      @else
        <div class="form-group">
            <label for="desde">Hora Inicio:</label>
            <select name="desde" id="desde" class="form-control">
            @for($horaInicio ; $horaInicio<=24 ; $horaInicio++)
              <option value="{{ $horaInicio; }}:00">{{ $horaInicio; }}:00</option>
            @endfor
        </select>
        </div>
        <div class="form-group">
          <label for="hasta">Hora Término:</label>
          <select name="hasta" id="hasta" class="form-control">
          @for($horaFin ; $horaFin<=24 ; $horaFin++)
            <option value="{{ $horaFin; }}:00">{{ $horaFin; }}:00</option>
          @endfor
        </select>
        </div>
      @endif   
        <div class="form-group">
          <label for="valor">Valor:</label>
          <input type="text" id="valor" name="valor" placeholder="Ingrese Valor" class="form-control" >
        </div> 
         <div class="form-group">
          {{ Form::submit('Establecer Precio', array('class' => 'btn btn-success')) }}
        </div>
      {{ Form::close() }}

    </div>
  </div>
</div>
@stop

laravel/app/views/rangos/edit.blade.php
/Users/Manteca/local/agendasmart/laravel/app/views/rangos/edit.blade.php

laravel/app/views/rangos/index.blade.php
@extends('layout.default')

@section('main')

<h1>Rangos para "{{ $agenda->nombre }}"</h1>
<h3>Tipo: {{ $tipo[$agenda->tipo] }}</h3>
<div class="col-md-10">
  <div class="row">
    <div class="col-md-11" style="top:15px;">
      @for ($i = 1; $i <= 7; $i++)
	    <h4>{{ $dias[$i] }}
      <?php 
      //$sala->UltimaHoraRango($_REQUEST['id_plaza'],1); 
      //if(str_replace(':00:00','',$sala->ultima_hora)!=24){
      ?>  
      <small>
      @if( ($agenda->tipo == 1440 && !isset($rangos[$i])) || ($agenda->tipo != 1440) )
        {{ link_to_route('agendas.rangos.new','Nuevo Rango de Precios',array($agenda->id_plaza, $i), array('class' => 'btn btn-primary btn-xs')) }}
      @endif
      @if($i > 1)
      <!-- <button type="button" class="btn btn-primary btn-xs" onclick="javascript:RepetirDiaAnterior({{ $i }},{{ $i-1 }},{{ $agenda->id_plaza }})">Repetir D&iacute;a Anterior</button> -->
      @endif
      </small>
    <?php //} ?>  
      </h4>
      <br>
        @if(isset($rangos[$i]))
    	  <ul>
        @foreach($rangos[$i] as $key => $rango)
        
    	  <li>Desde {{ $rango['desde'] }} 
        Hasta {{ $rango['hasta'] }}
        Valor: {{ $rango['valor'] }}
          {{ link_to_route('agendas.rangos.destroy', 'Quitar', array($agenda->id_plaza, $key), array('class'=> 'btn btn-small btn-danger','data-method' => 'delete', 'data-confirm' => "¿Estas seguro que deseas Quitar el rango de Horario?")) }}
        </li>
    	  @endforeach
    	  </ul>
        @endif
      <br>
      <hr>
      @endfor

    </div>
  </div>
</div>
@stop

laravel/app/views/rangos/show.blade.php
/Users/Manteca/local/agendasmart/laravel/app/views/rangos/show.blade.php