laravel/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', 'HomeController@frontpage');
Route::post('contacto', 'HomeController@contacto');
/* Calendario Publico INICIO*/
Route::get('agendas/calendario/{shortname?}/{grupo?}', array('as' => 'agenda.calendario', 'uses' => 'AgendasController@calendario'));
Route::get('reservas/events', array('as' => 'reservas.eventos', 'uses' => 'ReservasController@getEvents'));
Route::post('reservas/guardar', array('uses' => 'ReservasController@guardar'));
Route::post('reservas/horarioDisponible', array('as' => 'reservas.horario-disponible', 'uses' => 'ReservasController@horarioDisponible'));
Route::post('rango/precio', array('as' => 'rangos.precio', 'uses' => 'RangosController@getPrecio'));
Route::post('reservas', array('as' => 'reservas.store', 'uses' => 'ReservasController@store'));

/* Calendario Publico FIN */
/* Pago Reserva */
Route::get('pagos/proceso_reserva/{cliente_id}/{reserva_id?}', array('as'=>'pagos.procesoreserva','uses'=> 'PagosController@procesoReserva'));
Route::post('pagos/exito', array('uses'=> 'PagosController@exito'));
Route::post('pagos/fracaso', array('uses'=> 'PagosController@fracaso'));
Route::get('pagos/confirmarOrden', array('uses'=> 'PagosController@confirmarOrden')); // Antes del envio
Route::get('pagos/proceso_plan/{cliente_id}/{plan_id}', array('uses'=> 'PagosController@procesoPlan'));
//Flow function
// Route::get('flows/testconfirm',array('uses' => 'FlowsController@testConfirm'));
Route::post('flows/confirmar',array('uses' => 'FlowsController@confirmar')); // Duarnte el proceso de compra

Route::group(array('before' => 'auth'), function()
{
	//Admin
	Route::get('admin','AdminController@createClient');

	Route::get('portal', array('as' => 'portal', 'uses' => 'HomeController@dashboard'));
	Route::get('wiki','HomeController@wiki');

	//Pagos
	Route::resource('pagos', 'PagosController');

	//Horarios
	Route::resource('horarios', 'HorariosController');
	//Reservas
	Route::get('reservas/calendario/{grupo?}', array('as' => 'reservas.calendario', 'uses' => 'ReservasController@calendario'));
	Route::resource('reservas', 'ReservasController', array('except' => array('store','show')));

	//Route::get('rangos/{idplaza}', array('as' => 'rangos.index', 'uses'=>'RangosController@index'));
	//Route::get('agendas.rangos', array( 'uses'=>'RangosController@index'));

	//Agendas
	Route::resource('agendas', 'AgendasController');
	// Agregar Grupo
	Route::get('agenda_grupos/defecto/{id}', array('as' => 'agenda_grupos.defecto', 'uses' => 'AgendaGruposController@defecto'));
	Route::get('agenda_grupos/estado/{id}', array('as' => 'agenda_grupos.estado', 'uses' => 'AgendaGruposController@estado'));
	Route::resource('agenda_grupos', 'AgendaGruposController');
	//Rangos
	Route::get('agendas/{agendas}/diaa/{dia}', array('as' => 'agendas.rangos.new', 'uses' => 'RangosController@create'));
	Route::post('agendas/{agendas}/rangos', array('as' => 'agendas.rangos.store', 'uses' => 'RangosController@store'));
	Route::get('agendas/{agendas}/diar/{dia}', array('as' => 'agendas.rangos.duplicate', 'uses' => 'RangosController@duplicate'));
	Route::resource('agendas.rangos', 'RangosController', array('except' => array('create','store','edit','update')));
	//Precios Especiales
	Route::resource('precio_especiales', 'PrecioEspecialesController');

	Route::get('clientes/planCaducado/{cliente_id}',array('uses'=>'ClientesController@planCaducado'));
	Route::get('clientes/planUpgrade/{cliente_id}',array('uses'=>'ClientesController@planUpgrade'));

	Route::get('clientes/flowConfigIs/{cliente_id}', array( 'uses'=>'ClientesController@flowConfigIs')); // existe
	Route::get('clientes/flowConfig/{cliente_id}', array('as' =>'flowconfig.create', 'uses'=>'ClientesController@flowConfig')); // Crear
	Route::post('clientes/flowConfigStore/', array( 'uses'=>'ClientesController@flowConfigStore')); // Guardar
	Route::get('clientes/flowConfigShow/{cliente_id?}', array('as' =>'flowconfig.show',  'uses'=>'ClientesController@flowConfigShow')); // Ver
	Route::post('clientes/flowCertificate/', array( 'uses'=>'ClientesController@flowCertificate')); // descargar Certificado

	Route::get('exportar/reservas', array('uses' => 'ReservasController@exportReservas'));

	//
	Route::get('usuarios',array('as'=>'usuarios','uses'=>'UsersController@usuarioIndex'));
	Route::get('usuarios/create',array('as'=>'usuarios.create','uses'=>'UsersController@usuarioCreate'));
	Route::post('usuarios/store',array('as'=>'usuarios.store','uses'=>'UsersController@usuariostore'));
	Route::get('usuarios/{usuario_id}/edit',array('as'=>'usuarios.edit','uses'=>'UsersController@usuarioEdit'));
	Route::put('usuarios/{usuario_id}',array('as'=>'usuarios.update','uses'=>'UsersController@usuarioUpdate'));
	Route::delete('usuarios/{usuario_id}',array('as'=>'usuarios.destroy','uses'=>'UsersController@usuarioDestroy'));

	// Perfil
	Route::get('users/perfil', 'UsersController@perfil');
	Route::post('users/perfils', 'UsersController@perfilStore');
});

// Pruebas
Route::controller('pruebas','PruebasController');
// Confide routes

Route::get('users/create', 'UsersController@create');
Route::post('users', 'UsersController@store');
Route::get('users/login', array('as' => 'login', 'uses' => 'UsersController@login'));
Route::post('users/login', 'UsersController@doLogin');
Route::get('users/confirm/{code}', 'UsersController@confirm');
Route::get('users/forgot_password', 'UsersController@forgotPassword');
Route::post('users/forgot_password', 'UsersController@doForgotPassword');
Route::get('users/reset_password/{token}', 'UsersController@resetPassword');
Route::post('users/reset_password', 'UsersController@doResetPassword');
Route::get('users/logout', 'UsersController@logout');

laravel/app/models/AgendaGrupo.php
<?php

class AgendaGrupo extends \Eloquent {

	// Add your validation rules here
	public static $rules = [
			'nombre'	=>	'required',
			'agendas'	=>	'array|required'
		// 'title' => 'required'
	];

	// Don't forget to fill this array
	protected $fillable = ['nombre','agendas', 'default','cliente_id','estado', 'block', 'vista'];

	public function isDefault()
	{
		if($this->default)
			return $this;
	}

	public function selectGroup($id)
	{
		if($this->id == $id)
			return $this;	
	}

}

laravel/app/controllers/AgendaGruposController.php
<?php

class AgendaGruposController extends \BaseController {

	/**
	 * Display a listing of agenda_grupos
	 *
	 * @return Response
	 */
	public function index()
	{
		$agenda_grupos = AgendaGrupo::where('cliente_id', '=', Auth::user()->id_cliente )->get();
		foreach ($agenda_grupos as $value) {
			$value->agendas = json_decode($value->agendas);
		}
		// dd($value->agendas);
		$agendas_temp = Agenda::where('id_cliente', '=', Auth::user()->id_cliente )->get();
		foreach ($agendas_temp as $value) {
			$agendas[$value->id_plaza] = $value->nombre;
		}
		return View::make('agenda_grupos.index', compact('agenda_grupos','agendas'));
	}

	/**
	 * Show the form for creating a new agendagrupo
	 *
	 * @return Response
	 */
	public function create()
	{
		$agendas = Agenda::where('id_cliente', '=', Auth::user()->id_cliente )->get();
		$tipo_vista = Config::get('variables.tipo_agenda_vista');
		$tipo_vista_union = Config::get('variables.tipo_agenda_vista_union');
		return View::make('agenda_grupos.create', compact('agendas'))->withTipoVista($tipo_vista)->withTipoVistaUnion($tipo_vista_union);
	}

	/**
	 * Store a newly created agendagrupo in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$messages = array(
    	'agendas.required' => 'Se debe seleccionar al menos una agenda.',
		);
		$validator = Validator::make($data = Input::all(), AgendaGrupo::$rules, $messages);
		// validar que almenos un checkbox este seleccionado
		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator)->withInput();
		}
		if(is_array($data['agendas'])){
			foreach ($data['agendas'] as $value) {
				$agendas_ids[] = $value; 	
			}
		}
		$data['agendas'] = json_encode($agendas_ids);
		$data['cliente_id'] = Auth::user()->id_cliente;
		AgendaGrupo::create($data);

		return Redirect::route('agenda_grupos.index');
	}

	/**
	 * Display the specified agendagrupo.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$agendagrupo = AgendaGrupo::findOrFail($id);

		return View::make('agenda_grupos.show', compact('agendagrupo'));
	}

	/**
	 * Show the form for editing the specified agendagrupo.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$agendagrupo = AgendaGrupo::where('cliente_id', '=', Auth::user()->id_cliente )->find($id);
		$agendas = Agenda::where('id_cliente', '=', Auth::user()->id_cliente )->get();
		$tipo_vista = Config::get('variables.tipo_agenda_vista');
		$tipo_vista_union = Config::get('variables.tipo_agenda_vista_union');
		return View::make('agenda_grupos.edit', compact('agendagrupo','agendas'))->withTipoVista($tipo_vista)->withTipoVistaUnion($tipo_vista_union);
	}

	/**
	 * Update the specified agendagrupo in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$messages = array(
    	'agendas.required' => 'Se debe seleccionar al menos una agenda.',
		);

		$agendagrupo = AgendaGrupo::where('cliente_id', '=', Auth::user()->id_cliente )->findOrFail($id);

		$validator = Validator::make($data = Input::all(), AgendaGrupo::$rules);

		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator)->withInput();
		}

		if(is_array($data['agendas'])){
			foreach ($data['agendas'] as $value) {
				$agendas_ids[] = $value; 	
			}
		}
		$data['agendas'] = json_encode($agendas_ids);

		$agendagrupo->update($data);

		return Redirect::route('agenda_grupos.index');
	}

	/**
	 * Remove the specified agendagrupo from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$bloked = AgendaGrupo::where('cliente_id', '=', Auth::user()->id_cliente )->findOrFail($id)->block;
		if(!$bloked){
			//Agendagrupo::destroy($id);
			return Redirect::route('agenda_grupos.index');
		}else{
			
			return Redirect::route('agenda_grupos.index')->with('message','No se puede eliminar el registro')->with('message-type', 'warning');
		}
	}

	public function defecto($id)
	 {
	 		AgendaGrupo::where('cliente_id', '=', Auth::user()->id_cliente )->update(array('default' => false));
	 		$grupo = AgendaGrupo::where('cliente_id', '=', Auth::user()->id_cliente )->where('id', '=', $id)->firstOrFail();
	 		$grupo->default = true;
	 		$grupo->save();

	 		return Redirect::route('agenda_grupos.index');
	 } 

	 public function estado($id)
	 {
	 		//Agendagrupo::where('cliente_id', '=', Auth::user()->id_cliente )->update(array('default' => false));
	 		$grupo = AgendaGrupo::where('cliente_id', '=', Auth::user()->id_cliente )->where('id', '=', $id)->firstOrFail();
	 		$grupo->estado = !$grupo->estado;
	 		$grupo->save();

	 		return Redirect::route('agenda_grupos.index');
	 }

}

laravel/app/views/agenda_grupos/create.blade.php
@extends('layout.default')

@section('main')

<h1>Grupo</h1>

<div class="col-md-10">
  <div class="row">
    <div class="col-md-11" style="top:15px;">
    
	    {{ Form::open(array('route'=> 'agenda_grupos.store')) }}      
	    
		    <div class="form-group">
		      {{ Form::label('Nombre:') }}
		      {{ Form::text('nombre',Input::old('nombre'), array('id' => 'nombre', 'placeholder' => 'Ingrese Nombre del Grupo', 'class' => 'form-control')) }}
		      {{ $errors->first('nombre', '<p class="bg-danger has-success has-feedback"><small class="text-danger">:message</small></p>') }}
		    </div>
		    <div class="form-groupp">
		    	{{ Form::label('Tipo de Vista') }}
		    	{{ Form::select('tipo', $tipo_vista , null, array('id' => 'tipo')) }}
		    </div>
		    <div class="form-group">
		    	<h3>Seleccione las agendas que quieres agreagr a este grupo:</h3>
		    @foreach($agendas as $agenda)
				  <label class="checkbox-inline">
				    <input type="checkbox" id="agendas_{{ $agenda->id_plaza }}" class="tipo tipo_{{ $tipo_vista_union[$agenda->tipo] }}" name="agendas[]" value="<?php echo $agenda->id_plaza; ?>">{{ $agenda->nombre }} ({{ $agenda->tipo }})
				  </label> 
				@endforeach
					<br>
					{{ $errors->first('agendas', '<p class="bg-danger"><small class="text-danger">:message</small></p>') }}
				</div>
		    <div class="form-group">
		    	{{ Form::submit('Crear Grupo', array('class' => 'btn btn-success')) }}
		    </div>

		  {{ Form::close() }}

    </div>
  </div>
</div>
@stop

@section('javascript')
<script>
$(function(){


	$('.tipo').prop("disabled", true).prop('checked', false).parent().addClass('disable');
	$('.tipo_'+$('#tipo').val()).prop("disabled", false).parent().removeClass('disable');

	$('#tipo').change( function(){
		$('.tipo').prop("disabled", true).prop('checked', false).parent().addClass('disable');
		$('.tipo_'+$(this).val()).prop("disabled", false).parent().removeClass('disable');
	});
});
</script>
@stop

laravel/app/views/agenda_grupos/edit.blade.php
@extends('layout.default')

@section('main')

<h1>Grupo</h1>

<div class="col-md-10">
  <div class="row">
    <div class="col-md-11" style="top:15px;">
    
	    {{ Form::model($agendagrupo, array('route'=> array('agenda_grupos.update',$agendagrupo->id), 'method' => 'put')) }} 
	    
		    <div class="form-group">
		      {{ Form::label('Nombre:') }}
		      {{ Form::text('nombre',Input::old('nombre'), array('id' => 'nombre', 'placeholder' => 'Ingrese Nombre del Grupo', 'class' => 'form-control')) }}
		      {{ $errors->first('nombre', '<p class="bg-danger has-success has-feedback"><small class="text-danger">:message</small></p>') }}
		    </div>
		    <div class="form-groupp">
		    	{{ Form::label('Tipo de Vista') }}
		    	{{ Form::select('tipo', $tipo_vista , $agendagrupo->vista, array('id' => 'tipo', 'disabled' => true)) }}
		    </div>
		    <div class="form-group">
		    	<h3>Seleccione las agendas que quieres agreagr a este grupo:</h3>
		    @foreach($agendas as $agenda)
				  <label class="checkbox-inline">
				    <input type="checkbox" id="agendas_{{ $agenda->id_plaza }}" class="tipo tipo_{{ $tipo_vista_union[$agenda->tipo] }}" name="agendas[]" {{ in_array($agenda->id_plaza, json_decode($agendagrupo->agendas))?'checked':'' }} value="<?php echo $agenda->id_plaza; ?>">{{ $agenda->nombre }} ({{ $agenda->tipo }})
				  </label> 
				@endforeach
					<br>
					{{ $errors->first('agendas', '<p class="bg-danger"><small class="text-danger">:message</small></p>') }}
				</div>
		    <div class="form-group">
		    	{{ Form::submit('Crear Grupo', array('class' => 'btn btn-success')) }}
		    </div>

		  {{ Form::close() }}

    </div>
  </div>
</div>
@stop

@section('javascript')
<script>
$(function(){
	console.log($('#tipo').val());
	$('.tipo').prop("disabled", true).parent().addClass('disable');
	$('.tipo_'+$('#tipo').val()).prop("disabled", false).parent().removeClass('disable');

});
</script>
@stop

laravel/app/views/agenda_grupos/index.blade.php
@extends('layout.default')

@section('main')

<h1>Agrupar Agendas</h1>

<div class="col-md-10">
  <div class="row">
    <div class="col-md-11" style="top:15px;">
    {{ link_to_route('agenda_grupos.create','Crear Grupo',array(),array('class'=>'btn btn-xsmall btn-primary')) }}
    	<table class="table">
        <thead>
            <tr>
                <th data-field="nombre">NOMBRE</th>
                <th data-field="precios"><center>Agendas</center></th>
                <th data-field="precios"><center>Default</center></th>
                <th data-field="precios"><center>Estado</center></th>
                <th data-field="editar"><center>EDITAR</center></th>
                <th data-field="quitar"><center>QUITAR</center></th>
            </tr>
        </thead>
        <tbody>
        
        @foreach($agenda_grupos as $grupo)
          <tr>
              <td>{{ $grupo->nombre }}</td>
              <td>
              	<ul>
              	@foreach($grupo->agendas as $value)
              		<li>{{ $agendas[$value] }}</li>
              	@endforeach
              	</ul>
              </td>
              <td>
                @if($grupo->default)
                  <a href="{{ route('agenda_grupos.defecto', $grupo->id) }}">
                    <span class="glyphicon glyphicon-ok text-succes" aria-hidden="true"></span>
                  </a>
                @else
                  <a href="{{ route('agenda_grupos.defecto', $grupo->id) }}">
                    <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                  </a>
                @endif
              </td>
              <td>
                @if($grupo->estado)
                  <a href="{{ route('agenda_grupos.estado', $grupo->id) }}">
                    <span class="glyphicon glyphicon-ok text-succes" aria-hidden="true"></span>
                  </a>
                @else
                  <a href="{{ route('agenda_grupos.estado', $grupo->id) }}">
                    <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                  </a>
                @endif
              </td>
							<td>
  							<center>
                  {{ link_to_route('agenda_grupos.edit', 'Editar', $grupo->id, array('class'=> 'btn btn-small btn-warning')) }}
  							
  							</center>
							</td>

							<td>
  							<center>
                  @if(!$grupo->block)
                    {{ link_to_route('agenda_grupos.destroy', 'Quitar', $grupo->id, array('class'=> 'btn btn-small btn-danger','data-method' => 'delete', 'data-confirm' => "¿Estas seguro que deseas borrar la Agenda?")) }}
                  @endif
  							</center>
							</td>
                        
            </tr>
				@endforeach
        </tbody>
    </table>

    </div>
  </div>
</div>
@stop

laravel/app/views/agenda_grupos/show.blade.php
/Users/Manteca/local/agendasmart/laravel/app/views/agenda_grupos/show.blade.php